# Numpy Exercises

Q1. Import numpy

In [1]:
import numpy as np

Q2. Create an array of 10 zeros.

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Q3. Create an array of 10 fives

In [3]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

Q4. Create an array of 10 ones.

In [4]:
np.ones(10)*10

array([10., 10., 10., 10., 10., 10., 10., 10., 10., 10.])

Q5. Create an array of all the even integers from 10 to 50

In [5]:
np.arange(10, 51, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

Q6. Create an array of the integers from 10 to 50

In [6]:
np.arange(10, 50, 1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

Q7. Create a 3x3 identity matrix (Hint - There is an in-built function for this)

In [7]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Q8. Create a 3x3 matrix with values ranging from 0 to 8

In [8]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Q9. Use NumPy to generate a random number between 0 and 1

In [9]:
np.random.rand(1)

array([0.64505607])

Q10. Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution (Note - Everyone will have different values)

In [10]:
np.random.randn(25)

array([-0.7403272 , -0.18668657,  0.31302909,  0.15090898,  1.95426508,
       -0.22228708,  1.36749432,  0.87997164, -0.76681212,  0.30915284,
        0.66529995, -0.37851583, -1.14898754, -0.39561853, -0.31230093,
       -0.65457173, -0.51098091,  0.12025553, -0.63473662,  0.11338593,
       -1.24283729,  0.39450962, -0.55107951,  0.27537248,  0.23087181])

Q11. Create an array of 20 linearly spaced points between 0 and 1

In [11]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## This is your base Matrix for the questions hence forth

```
mat = np.arange(1,26).reshape(5,5)
mat
```



```
array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])
```



**Note - Make sure to run the code cell to create the matrix 'mat' before going ahead.**




Q12. Index first 3 rows and 2 columns

In [12]:
mat = np.arange(1, 26).reshape(5, 5)
mat[:3, :2]

array([[ 1,  2],
       [ 6,  7],
       [11, 12]])

Q13. Index and select the value 20

In [13]:
mat[3, 4]

np.int64(20)

Q14. Index and select the values of the first 3 rows of 2nd column

In [14]:
mat[:3, 1]

array([ 2,  7, 12])

Q15. Index and select the final row

In [15]:
mat[-1]

array([21, 22, 23, 24, 25])

Q16. Index and select the values of the last and second last row

In [16]:
mat[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

Q17. Sum of all values in the matrix `mat`

In [28]:
mat.sum()

np.int64(325)

Q18. Get standard deviation of all values in the matrix `mat`

In [29]:
mat.std()

np.float64(7.211102550927978)

Q19. Sum of all values of columns in matrix `mat`

In [30]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

---

# Pandas Exercises

Q1. Import pandas and read in the `population_by_county.xlsx` file into a dataframe called `pop`.

In [1]:
import pandas as pd

pop = pd.read_excel("population_by_county.xlsx")

Q2. Display the head of the created dataframe

In [5]:
pop.head()

,County,State,2010Census,2017PopEstimate
0,Abbeville County,South Carolina,25417,24722
1,Acadia Parish,Louisiana,61773,62590
2,Accomack County,Virginia,33164,32545
3,Ada County,Idaho,392365,456849
4,Adair County,Iowa,7682,7054


Q3. Extract column names

In [6]:
pop.columns

Index(['County', 'State', '2010Census', '2017PopEstimate'], dtype='str')

Q4. How many States are represented in this data set?

In [7]:
pop['State'].nunique()

51

Q5. Get a list or array of all the states in the data set.

In [8]:
pop['County'].value_counts().head()

County
Washington County    30
Jefferson County     25
Franklin County      24
Jackson County       23
Lincoln County       23
Name: count, dtype: int64

Q6. What are the five most common County names in the U.S.?

In [17]:
print("test")

test


Q7. What are the top 5 most populated Counties according to the 2010 Census?

In [ ]:
pop.sort_values('2010Census', ascending=False).head()

Q8. What are the top 5 most populated States according to the 2010 Census?

Q9. How many Counties have 2010 populations greater than 1 million?

Q10. How many Counties don't have the word "County" in their name?

Q11. Add a column that calculates the percent change between the 2010 Census and the 2017 Population Estimate

Q12. What States have the highest estimated percent change between the 2010 Census and the 2017 Population Estimate?

---